[tool.poetry]
name = "waveform-collapse"
version = "0.1.0"
description = ""
authors = ["Felix Tripier <tripier@ionq.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
